#!/bin/bash

if [ ! -f /usr/local/percona/pmm2/config/pmm-agent.yaml ]; then
    /usr/sbin/pmm-agent setup --config-file=/usr/local/percona/pmm2/config/pmm-agent.yaml \
        --server-address=127.0.0.1:8843 --server-insecure-tls --server-username=admin \
        --server-password=admin
fi


/usr/sbin/pmm-agent --config-file=/usr/local/percona/pmm2/config/pmm-agent.yaml

